[workspace]
members = [
    "fx",
    "fx-core",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
description = "llm serving."

[workspace.dependencies]
anyhow = "1.0.80"
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.4.0"}